name: Test Manual Pipeline

on:
  # manual triggers with parameters
  workflow_dispatch:
    inputs:
        test_val:
            description: "Test Value"
            required: true

jobs:
  test:
    name: Test Color

    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out source repository
      uses: actions/checkout@v2
      
    - name: This fails
      run: | 
        if (exit 1); then
          echo "Failure=0" >> $GITHUB_ENV
        else
          echo "Failure=1" >> $GITHUB_ENV
          message=`cat test.txt`
          echo "FailureMessage=$message" >> $GITHUB_ENV
        fi
      
    - name: Discord notification
      if: ${{ env.Failure != 0 }}
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: ${{ env.FailureMessage }}