name: Test Manual Pipeline

on:
  # manual triggers with parameters
  workflow_dispatch:
    inputs:
        test_val:
            description: "Test Value"
            required: true

jobs:
  test:
    name: Test Color

    runs-on: ubuntu-latest

    steps:
      
    - name: This fails
      run: | 
        if exit -1; then
          echo "Good"
          echo "::set-env name=Failure::0"
        else
          echo "Bad"
          echo "::set-env name=Failure::1"
        fi
      
    - name: Discord notification
      if: ${{ Failure != 0 }}
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'Something'